[package]
name = "breezy1214/ezinput"
version = "0.1.0"
description = "Fluent chainable builder API for Roblox Input Action System"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Janitor = "howmanysmall/janitor@1.18.3"
