name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rokit
        uses: roblox-ts/setup-rokit@v0.1.2

      - name: StyLua check
        run: stylua --check src/

      - name: Selene lint
        run: selene src/
